name: 'OLLAMA MODEL Build and Push to Artifact Registry'

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: 'Build & Push Ollama Docker Image'
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GAR_LOCATION: asia-southeast2
      REPOSITORY: ielts-repo
      IMAGE_NAME: foodvqa-ollama
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-foodvqa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Docker Auth for Artifact Registry
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          set -e
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          IMAGE_URI="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:latest"
          echo "🚀 Building and pushing image: $IMAGE_URI"

          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"
